---
title: "FA20 Graduate Campaign Quarterly Ad Analytics Project: FY20 Q1"
author: "Office of Marketing and Brand Management"
date: "3/25/2020"
output:
  pdf_document:
fontsize: 11pt
mainfont: Calibri
sansfont: Calibri
monofont: Calibri
geometry: margin=1in
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r include=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
library(tinytex)
library(hms)
library(lubridate)
library(stringr)
```


```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```


```{r}
NewData <- read.csv("C:/Users/christine.iyer/Box/quarterly-ad-analytics-projects/FlowchartGrad.csv", header = T, stringsAsFactors = F)
```

```{r}
NewDataFY20Q1 <- NewData %>% filter(Quarter == "FY20Q1" & str_detect(AdSet, "GR_ALL"))
NewDataFY20Q1 <- NewDataFY20Q1[,c(4:11)]
knitr::kable(NewDataFY20Q1, "latex", caption = "FY20 Q1 Graduate Campaign", booktabs = T)%>%
kable_styling(full_width = T)  %>%
  row_spec(0, angle = -45)
```
