---
title: "Quarterly Inquiries by Program and Audience"
author: "Office of Marketing and Brand Management"
date: "5/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(tidyverse)
library(lubridate)
library(knitr)
library(forecast)
```

## Different ways to see the number of inquiries generated by Agency Campaigns year over year. 

### 1.

```{r}
Forms <- read.csv("C:/Users/christine.iyer/Box/quarterly-ad-analytics-projects/ThankYouFormCompletions.csv", header = T, stringsAsFactors = F)

DCForms <- Forms %>% mutate(Program_Audience = ifelse(str_detect(Initial.Referral.Source,"HS"), "HS", ifelse(str_detect(Initial.Referral.Source, "TR"), "TR", ifelse(str_detect(Initial.Referral.Source, "DC"), "DC", ifelse(str_detect(Initial.Referral.Source, "GR"), "GR", "Other" ))))) %>%  #ifelse(str_detect(Initial.Referral.Source, "OL"),"OL",
                                                                                                                                                                                                                             
  mutate(Date = as.Date(Initial.Source.Date, format = "%m/%d/%Y"),
         LandingPage = 
           ifelse(Date <= "2019-08-01","/everyone",
                  ifelse(Date > "2019-08-01" & Date < "2020-02-18", "/here", "/excel")),
         FY = ifelse(Date < "2019-07-01", "FY19","FY20"), 
         Quarter = paste0((FY),"Q",quarter(Date, with_year = FALSE, fiscal_start = 7))
    
  ) %>% select(FY, Quarter,Date, everything())


kable(DCForms %>% filter(Program_Audience != "Other") %>% group_by(FY) %>% summarise(`Total Inquiries this Quarter` = n()))

Q3Forms <- DCForms %>% filter(Program_Audience!= "Other" & str_detect(Quarter, "3"))
kable(Q3Forms %>%  
        group_by(FY, Quarter,Program_Audience) %>% 
        summarise(`Total Inquiries this Quarter` = n()) %>% spread(Program_Audience, `Total Inquiries this Quarter`) %>% select(Quarter, HS, TR, GR, DC))


```


```{r}
library(zoo)
QForms <- DCForms %>% filter(FY != "NA" ) %>% 
        group_by(Quarter,Program_Audience) %>% 
        summarise(`Total Inquiries this Quarter` = n()) %>% spread(Program_Audience, `Total Inquiries this Quarter`) %>% select( HS, TR, GR, DC)
#QForms$Date <- c("2019-09", "2019-12", )
QFormsNew <- QForms %>% select(-Quarter)
HS <- QForms %>% select(HS)
TR <- QForms %>% select(Quarter, TR)
GR <- QForms %>% select(Quarter, GR)
DC <- QForms %>% select(Quarter, DC)
a <- QFormsNew %>% select(-Quarter)


  HS = c(32, 48,144,141,85,29,49,0) 
  TR = c(13, 28,75,65,48,37,47,0) 
  GR = c(12,30,72,76,81,57,35,0) 
  DC = c(2,8,10,2,3,11,9,0)
  
a <- cbind.data.frame(HS,TR,GR,DC)  
```

```{r}
USMCol <- c("#0e1033", "#f5a800")

tsHS <- ts(HS, start = c(2019, 1), frequency = 4)
#print(tsHS)
HS <- ggseasonplot(tsHS, col = USMCol, main = "HS Students")+theme_bw()
```

```{r}
tsTR <- ts(TR, start = c(2019, 1), frequency = 4)
#print(tsTR)
TR <- ggseasonplot(tsTR, col = USMCol, main = "Transfer Program")+theme_bw()
```

```{r}
tsGR <- ts(GR, start = c(2019, 1), frequency = 4)
#print(tsGR)
GR <- ggseasonplot(tsGR, col = USMCol, main = "Graduate Program")+theme_bw()
```

```{r}
tsDC <- ts(DC, start = c(2019, 1), frequency = 4)
#print(tsDC)
DC <- ggseasonplot(tsDC, col = USMCol, main = "DC Program", lty = 4)+theme_bw()
```

### 2.

```{r}
DCForms$Program_Audience <- factor(DCForms$Program_Audience, levels = c("HS", "TR", "GR", "DC"))

kable(DCForms %>% filter(FY != "NA" & Quarter != "FY20Q4") %>% 
        group_by(Quarter,Program_Audience) %>% 
        summarise(`Total Inquiries this Quarter` = n()) %>% spread(Program_Audience, `Total Inquiries this Quarter`) %>% select(Quarter, HS, TR, GR, DC))
```

### 3.

```{r}

DCForms %>% filter(FY != "NA" & Quarter != "FY20Q4" & Program_Audience!= "Other" & Program_Audience != "OL") %>% 
        group_by(Quarter,Program_Audience) %>% 
        summarise(`Total Inquiries this Quarter` = n()) %>%  
  ggplot(., aes(Quarter, `Total Inquiries this Quarter`)) + 
  geom_bar(stat = "identity", fill = "steelblue") +facet_wrap(~Program_Audience, ncol = 4) +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) 



```

### 4.

```{r}

library(patchwork)

patchwork <- (HS | TR) / (GR | DC)
patchwork + plot_annotation(
  subtitle = 'FY19 vs FY20',
  title = 'Year Over Year Inquiry Comparison by Quarter and Program',
  caption = 'FY20 Q4 to be determined'
)


```

### Conclusions

* Comparing FY20 Q3 to FY19 Q3, we are down. 

* When looking at the cumulative sums, we are currently ahead of where we were at the end of Q3 FY19. 