---
title: "FA20 Undergraduate Campaign Quarterly Ad Analytics Project: FY20 Q3"
author: "Office of Marketing and Brand Management"
date: "3/25/2020"
output:
  pdf_document:
fontsize: 11pt
mainfont: Calibri
sansfont: Calibri
monofont: Calibri
geometry: margin=1in
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r include=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
library(tinytex)
library(hms)
library(lubridate)
library(stringr)
library(tidyr)
```


```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```


```{r}
NewData <- read.csv("C:/Users/christine.iyer/Box/quarterly-ad-analytics-projects/Flowchart.csv", header = T, stringsAsFactors = F)
```

```{r}
NewDataFY19Q3 <- NewData %>% filter(Quarter == "FY20Q3" & str_detect(AdSet, "HS")) %>%  separate(Vendor, c("Vendor", "Medium")) %>% select(Medium, Vendor, Quarter, Impressions:End_Date) %>% arrange(Medium, Vendor)
#NewDataFY19Q3 <- NewDataFY19Q3[,c(4:13)]
landscape(knitr::kable(NewDataFY19Q3, "latex", caption = "FY20 Q3 Graduate Campaign Targeting All Audiences", booktabs = T))%>%
kable_styling(full_width = T)  %>%
  row_spec(0, angle = -45) %>%
  pack_rows("Display", 1, 4) %>%
  pack_rows("Video", 7, 13) %>%
  pack_rows("Instagram Stories", 5, 6) 
  
```

```{r}
NewDataFY19Q3 <-  NewDataFY19Q3 %>%
  mutate(Vendor = Vendor, 
         Medium = Medium,
         Impressions = Impressions,
    CTR = cell_spec(CTR, "latex", color = ifelse(CTR == "0.38%", "red", "black")),
    UPV = UPV, 
    Cost = cell_spec(Cost, "latex", color = ifelse(Cost == "$ 4939.1", "red", "black"))
    
  ) %>%
  select(Vendor, Impressions,CTR, UPV,Cost)


landscape(kable(NewDataFY19Q3, format = "latex", escape = F, caption = "FY20 Q3 Graduate Campaign Targeting All Audiences", booktabs = T))%>%
kable_styling(full_width = T)  %>%
  row_spec(0, angle = -45) %>%
  pack_rows("Display", 1, 4) %>%
  pack_rows("Video", 7, 13) %>%
  pack_rows("Instagram Stories", 5, 6) 


  # kable(format = "latex", escape = F, booktabs = T) %>%
  # kable_styling(full_width = T)%>%
  # row_spec(0, angle = -45) %>%
  # pack_rows("Display", 1, 4)%>%
  # pack_rows("IG Stories", 5, 6)%>%
  # pack_rows("Video", 7, 13)
```


  

```{r}
NewDataFY19Q3 <- NewData %>% filter(Quarter == "FY20Q3" & str_detect(AdSet, "FA21_UG_IN_PIN_DISP_BR")) %>%  separate(Vendor, c("Vendor", "Medium")) %>% select(Medium, Vendor, Quarter, Impressions:End_Date) %>% arrange(Medium, Vendor)
#NewDataFY19Q3 <- NewDataFY19Q3[,c(4:13)]
landscape(knitr::kable(NewDataFY19Q3, "latex", caption = "FY20 Q3 Graduate Campaign Targeting All Audiences", booktabs = T))%>%
kable_styling(full_width = T)  %>%
  row_spec(0, angle = -45) 
  
```

Inquiries

```{r}
Forms <- read.csv("C:/Users/christine.iyer/Box/quarterly-ad-analytics-projects/ThankYouFormCompletions.csv", header = T, stringsAsFactors = F)

DCForms <- Forms %>% filter(str_detect(Initial.Referral.Source,"HS")) %>% 
  mutate(
    Date = as.Date(Initial.Source.Date, format = "%m/%d/%Y"),
    FY = ifelse(Date < "2019-07-01", "FY19","FY20"), 
    Quarter = paste0((FY),"Q",quarter(Date, with_year = FALSE, fiscal_start = 7))
    
  ) %>% select(FY, Quarter,Date, everything())

DCForms <- DCForms %>% filter(str_detect(Initial.Referral.Source, "HS"), str_detect(Quarter, "3"))
kable(DCForms %>%  
        group_by(FY, Quarter) %>% 
        summarise(`Total Inquiries this Quarter` = n()))
```


