---
title: "FA20 Campus Tours Campaign Quarterly Ad Analytics Project: FY20 Q3"
author: "Office of Marketing and Brand Management"
date: "`r Sys.Date()`"
output:
  pdf_document:
fontsize: 11pt
mainfont: Calibri
sansfont: Calibri
monofont: Calibri
geometry: margin=1in
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r include=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
library(tinytex)
library(hms)
library(lubridate)
library(stringr)
```


```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```


```{r}
NewData <- read.csv("C:/Users/christine.iyer/Box/quarterly-ad-analytics-projects/FlowchartCampusTours.csv", header = T, stringsAsFactors = F)


```

__Campus Tours__

```{r}
NewDataFY19Q3 <- NewData %>% filter(Quarter == "FY20Q3" )
NewDataFY19Q3 <- NewDataFY19Q3[,c(4:12)]
landscape(kable(NewDataFY19Q3, "latex", caption = "FY20 Q3 Campus Tours Campaign for High School Audiences", booktabs = T))%>%
kable_styling(full_width = T)  %>%
 row_spec(0, angle = -45)
```

* Event Registration changed to Virtual Tour ads which began 4/1/2020. 

```{r}


# __Graduate Degree__
# NewDataFY19Q3 <- NewData %>% filter(Quarter == "FY20Q3" & str_detect(AdSet,"GR" ))
# NewDataFY19Q3 <- NewDataFY19Q3[,c(4:12)]
# landscape(kable(NewDataFY19Q3, "latex", caption = "FY20 Q3 Working Adult Campaign", booktabs = T))%>%
# kable_styling(full_width = T)  
#%>%
  #row_spec(0, angle = -45)
```
